lifull-dev/bucky-core

README.md
docker-compose.dev-with-bm.yml

fix readme

---

exe/bucky
spec/test_config/hierarchy_config/test_config_hierarchy.yml
spec/test_config/test_config.yml
spec/utils/yaml_load_spec.rb

Fix test_config.
And fix exe/bucky for rubocop.

move test config to spec

---

README.md

add link to hands-on and add snake case remaind

---

lib/bucky/version.rb

change to 0.9.1

---

example/README.md
example/bucky-management/.bucky_home
example/bucky-management/README.md
example/bucky-management/config/bucky_config.yml
example/bucky-management/config/e2e_config.yml
example/bucky-management/config/linkstatus_config.yml
example/bucky-management/config/test_db_config.yml
example/bucky-management/services/README.md
example/bucky-management/services/bucky_example/pc/pageobject/github_search_list.rb
example/bucky-management/services/bucky_example/pc/pageobject/github_top.rb
example/bucky-management/services/bucky_example/pc/parts/github_search_list.yml
example/bucky-management/services/bucky_example/pc/parts/github_top.yml
example/bucky-management/services/bucky_example/pc/scenarios/e2e/search_and_assert.yml
example/bucky-management/services/bucky_example/pc/scenarios/linkstatus/github_top.yml
example/bucky-management/system/evidences/README.md
example/bucky-management/system/evidences/screen_shots/README.md
example/bucky-management/system/logs/README.md
example/hands-on/README.md
template/make_page/pc/pageobject/sample_page.rb
template/make_page/sp/pageobject/sample_page.rb
template/make_page/tablet/pageobject/sample_page.rb

Add new example. Connect to Bucky-management.

add bm connect example

---

.circleci/config.yml
.codeclimate.yml
README.md

1. Set Code Climate test coverage report
2. Disable rubocop
3. Add badges in README

disable rubocop and set test coverage

---

Gemfile.lock
lib/bucky/utils/config.rb
spec/utils/config_not_in_template.yml

deal with config not in template

---

Gemfile.lock
lib/bucky/test_equipment/selenium_handler/webdriver_handler.rb

正し名前に変更しました。
https://w3c.github.io/webdriver/#compatibility

fix option name

---

lib/bucky/test_equipment/user_operation/user_operation_helper.rb
spec/test_equipment/user_operation/user_operation_helper_spec.rb

I need "switch to the named window”.
Where should i make its test code?

I need "switch to the named window"

---

example/bucky-management/config/e2e_config.yml
example/hands-on/config/e2e_config.yml
lib/bucky/test_equipment/selenium_handler/webdriver_handler.rb
spec/test_equipment/selenium_handler/webdriver_handler_spec.rb
spec/utils/e2e_config.yml
system_testing/test_bucky_project/config/e2e_config.yml
template/new/config/e2e_config.yml

To use chromedriver flags at e2e_config.yml
https://peter.sh/experiments/chromium-command-line-switches/

Add handling chromedriver flags

---

Gemfile.lock
lib/bucky/test_equipment/pageobject/base_pageobject.rb

get waring if a part file is empty

continue if part file is empty

---

Gemfile.lock
lib/bucky/test_equipment/user_operation/user_operation_helper.rb
spec/test_equipment/user_operation/user_operation_helper_spec.rb

Fix some switch user operations.
Switch next and last windows by the index of window_handles.
window_handles reference:
https://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/Driver.html#window_handles-instance_method
Add switch back to last window after closing current window.

fix switch add rspec

---

.circleci/config.yml
.dockerignore

Fix for pushing to docker hub!

Fix dockerignore

---

.circleci/config.yml
Gemfile.lock
bucky-core.gemspec

Fix gemfile

---

.circleci/config.yml

Fix for pushing latest tag image.

Fix config.yml

---

Gemfile.lock
lib/bucky/core/test_core/test_class_generator.rb
lib/bucky/test_equipment/verifications/service_verifications.rb
spec/test_equipment/verifications/service_verifications_spec.rb

Fix empty proc bug
And add exception handler in verification.

fix bugs when proc is empty

---

Dockerfile
Dockerfile.system-test

https://github.com/lifull-dev/bucky-core/blob/master/lib/bucky/utils/config.rb#L51
This line needs ip command.

Add iproute2-minimal.

---

lib/bucky/core/test_core/test_manager.rb

AsIs:
Only final round result is included in a report file
ToBe:
Total result of all rounds is include in a report file.
```
[
{
case_1: {case_count: 10, success_count: 6, failure_count: 4},
case_2: {case_count: 10, success_count: 8, failure_count: 2}
},
{
case_1: {case_count: 4, success_count: 4, failure_count: 0},
case_2: {case_count: 2, success_count: 0, failure_count: 2}
}
]
AsIs -> case_count: 6, seccess_count : 4, failure_count: 2
ToBe -> case_count: 20, seccess_count : 18, failure_count: 2
```

Fix round report

---

README.md
exe/bucky
lib/bucky/core/database/test_data_operator.rb
lib/bucky/core/test_core/test_manager.rb
spec/core/database/test_data_operetor_spec.rb

Related. https://github.com/lifull-dev/bucky-management/pull/54

Add base_fqdn to use in bucky-management

---

lib/bucky/test_equipment/user_operation/user_operation_helper.rb

This reverts commit 137a3fa71b6e6a3d8dcaa3e9a9dd403701ee81dc.

Revert "do not merge"
